### ISSUE TITLE
Hello, I have turned on family monitoring. Is it not working properly?

### ISSUE THREAD

**Issue by akasls** [DrWarpMan/steam-hour-booster#2]
I'm using docker and I get the error "Error: Encrypted message authentication failed", is this because I have Steam's home monitoring enabled. Will you support the ability to use Steam with home monitoring enabled in the future? Thank you!

**Comment by DrWarpMan** [comment]
Hi, I am kinda confused, are you talking about [Family Sharing](https://store.steampowered.com/promotion/familysharing) or [Family View](https://help.steampowered.com/en/faqs/view/6B1A-66BE-E911-3D98)?

**Comment by DrWarpMan** [comment]
I setup the Family View, and it seems to be working fine. No errors whatsoever.

Can you check if the error occurs if you disable the Family View?
Can you also test whether it is an issue that is tied to your account specifically, and maybe try it on a completely different account?
