### ISSUE TITLE
Conditions

### ISSUE THREAD

**Issue by Verssgn** [DrWarpMan/steam-hour-booster#3]
Is there a way to make it only farm when a certain software is opened?

My situation is that I am using software from Steam, "Blender," which doesn't launch through Steam when you open files. So, I am using Steam Hour Booster to track how much time I spend working in Blender. It's inconvenient to have to open and close it each time. Is there a way I could make it recognize when Blender is opened? The only method I've found is to have a separate running script that checks every couple of minutes if Blender is running and then terminates or turns on Steam Hour Booster accordingly.

Thanks.

**Comment by DrWarpMan** [comment]
This is a very, very specific scenario and I don't think there is a way I could implement such a feature without running into problems. Also it would be problematic to get it to work with a dockerized version of this program.

Unfortunately, the best option is to create a separate script that checks if you have Blender running or not and turns the program on or off, respectively.

**Comment by Verssgn** [comment]
Makes sense, thanks for the reply!
