### ISSUE TITLE
Doesn't roll clock on all games, how to solve this? 

### ISSUE THREAD

**Issue by Marllling** [DrWarpMan/steam-hour-booster#5]
For example, exposing the game CS:GO/Unturned the clock is not wound up, there are no errors. How can this be solved? Thanks in advance! <3 
![1](https://github.com/user-attachments/assets/55e64108-aae8-4b27-8206-b077f425fbd8)
![2](https://github.com/user-attachments/assets/2957687d-200d-4f25-b3b9-2ebee5b07704)

**Comment by Marllling** [comment]
At the same time it works for example on Dota 2/Team Fortress 2.

**Comment by DrWarpMan** [comment]
I used this with CS:GO (CS 2)  and it worked in the past. Have you waited long enough to see if it actually adds playtime for those  games?

Try adding `"online": true` to your account configuration, and then check your profile and see if it shows that you are "in game".

e.g.:
```json
[
    {
        "username": "foo",
        "password": "bar",
        "games": [730],
        "online": true
    }
]

**Comment by DrWarpMan** [comment]
I used this with CS:GO (CS 2)  and it worked in the past. Have you waited long enough to see if it actually adds playtime for those  games?

When it launches the game, does it show that you are actually in-game, playing CS2 _on your Steam profile_?

**Comment by Marllling** [comment]
Started the game once through the steem client manually, but through the script cs2 does not run. Only Dota 2 and Team Fortress 2 games work (cs2, unturned do not work).

**Comment by Marllling** [comment]
my steam profile: https://steamcommunity.com/profiles/76561199733567287

**Comment by Marllling** [comment]
![image](https://github.com/user-attachments/assets/0fa65fb4-f171-45ad-a3be-9ad4faaf9a7f)

**Comment by Marllling** [comment]
It seems to be fixed, the problem was with the styme servers, please tell me how to add another account? I follow the syntax, add another one, there are no errors, but the second account does not se
![Безымянный](https://github.com/user-attachments/assets/292f6d8c-0bad-48d0-a8d1-5c1208e40550)
e.

**Comment by DrWarpMan** [comment]
Like this:
```json
[
    {
        "username": "foo1",
        "password": "bar1",
        "games": [730]
    },
    {
        "username": "foo2",
        "password": "bar2",
        "games": [730]
    }
]
